[mgr]
  layout = [ 1, 4, 3, ]
  sort_by = "alphabetical"
  sort_sensitive = true
  sort_reverse = false
  sort_dir_first = true
  linemode = "size"
  show_hidden = false
  show_symlink = true

[preview]
  tab_size = 2
  max_width = 600
  max_height = 900
  cache_dir = "$HOME/.cache/yazi"
  image_quality = 90

[opener]
  edit = [
    { run = 'hx "$0"', block = true, for = "unix" },
  ]
  image = [
    { run = 'pix "$0"', block = true, for = "unix" },
  ]
  video = [
    { run = 'mpv --autofit=10% "$0"', block = true, for = "unix" },
  ]

[open]
  rules = [
    { mime = "text/*", use = "edit" },
    { mime = "image/*", use = "image" },
    { mime = "video/*", use = "video" },
  ]
